sonar.projectKey=mb-dot-dev_warsaw-self-signed-rest-api
sonar.organization=mb-dot-dev

sonar.sources=app
sonar.exclusions=**/__pycache__/**

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Language and version
sonar.language=python
sonar.python.version=3.15

# Tests & coverage
sonar.tests=tests
sonar.python.coverage.reportPaths=build/coverage.xml
sonar.coverage.exclusions=tests/**
