AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for the Lambda function

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
  QueueArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: ARN of the SQS queue
    Default: /sqs/oslo/queue-arn
  RoleName:
    Type: String
    Description: Name of the IAM role for the Lambda function

Outputs:
  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${RoleName}-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !Ref QueueArn
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/projects/warsaw/*"
              - Effect: Allow
                Action: kms:Decrypt
                Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Ref RoleName
