name: Main
run-name: Build & deploy 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: warsaw

permissions:
  id-token: write # REQUIRED for OIDC
  contents: read

jobs:
  prepare:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.vars.outputs.project_name }}
    steps:
      - id: vars
        run: |
          echo "project_name=${{ env.PROJECT_NAME }}" >> "$GITHUB_OUTPUT"

  sonarqube:
    name: SonarQube
    uses: mb-dot-dev/reusable-workflows/.github/workflows/python-test-sonar.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-lambda-zip:
    name: Build Lambda ZIP
    needs:
      - sonarqube
    uses: mb-dot-dev/reusable-workflows/.github/workflows/build-lambda-zip.yaml@main

  cfn-lint:
    name: CloudFormation Lint
    uses: mb-dot-dev/reusable-workflows/.github/workflows/cfn-lint.yaml@main

  deploy-resource-group:
    name: Deploy Resource Group
    needs:
      - prepare
      - cfn-lint
    uses: mb-dot-dev/reusable-workflows/.github/workflows/deploy-cloudformation.yaml@main
    secrets: inherit
    with:
      stack-name: ${{ needs.prepare.outputs.project_name }}-resource-group
      template: aws/resource-group.yml
      project: ${{ needs.prepare.outputs.project_name }}
      parameter-overrides: >-
        ProjectName=${{ needs.prepare.outputs.project_name }}

  deploy-iam-role:
    name: Deploy IAM Role
    needs:
      - prepare
      - cfn-lint
    uses: mb-dot-dev/reusable-workflows/.github/workflows/deploy-cloudformation.yaml@main
    with:
      stack-name: ${{ needs.prepare.outputs.project_name }}-iam-role
      template: aws/iam-role.yml
      parameter-overrides: >-
        ProjectName=${{ needs.prepare.outputs.project_name }},
        RoleName=${{ needs.prepare.outputs.project_name }}-lambda
      project: ${{ needs.prepare.outputs.project_name }}
    secrets: inherit

  deploy-lambda:
    name: Deploy Lambda
    needs:
      - prepare
      - build-lambda-zip
      - deploy-iam-role
      - cfn-lint
    uses: mb-dot-dev/reusable-workflows/.github/workflows/deploy-lambda.yaml@main
    with:
      project: ${{ needs.prepare.outputs.project_name }}
      lambda-execution-role-arn: ${{ fromJSON(needs.deploy-iam-role.outputs.stack-outputs-json).LambdaExecutionRoleArn }}
    secrets:
      DEPLOY_ROLE_ARN: ${{ secrets.DEPLOY_ROLE_ARN }}
